version: "3"
services:
  lightgbm-dtreeviz:
    container_name: lightgbm-dtreeviz
    image: lightgbm-dtreeviz:1.0
    build:
      context: ./docker
      dockerfile: ./LightGBM-dtreeviz/Dockerfile
    volumes:
      - ./:/work
    working_dir: /work
    ports:
      - 8888:8888
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token=''
