version: "3"
services:
  Bayesian-Opt:
    container_name: Bayesian-Opt
    image: Bayesian-Opt:1.0
    build:
      context: ./docker
      dockerfile: ./Bayesian-Opt/Dockerfile
    volumes:
      - ./:/work
    working_dir: /work
    ports:
      - 8888:8888
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token=''
