version: "3"
services:
  ngboost:
    container_name: ngboost
    image: ngboost:1.0
    build:
      context: ./docker
      dockerfile: ./NGBoost/Dockerfile
    volumes:
      - ./:/work
    working_dir: /work
    ports:
      - 8888:8888
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token=''
