version: "3"
services:
  ax:
    container_name: ax
    image: ax:1.0
    build:
      context: ./docker
      dockerfile: ./Ax/Dockerfile
    volumes:
      - ./:/work
    working_dir: /work
    ports:
      - 8888:8888
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token=''
